## Working with NumPy

In [1]:
import numpy as np

In [2]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


## The NumPy array (ndarray)

In [3]:
a = np.arange(6) # create a 1D array

In [4]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [5]:
print( a )

[0 1 2 3 4 5]


In [6]:
dir( a )

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [7]:
type( a )

numpy.ndarray

In [8]:
type( a[0] )

numpy.int32

In [9]:
print( a[1] )

1


In [10]:
print( a[:3] )

[0 1 2]


In [11]:
print( a[:5] )

[0 1 2 3 4]


In [13]:
a_list = [ ['a', 1, 2.0], 1, 2, 3 ]

In [14]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
a_list     list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


### attributes associated with the array

In [15]:
a.ndim # the number of dimensions

1

In [16]:
a.shape # number of elements per dimension

(6,)

In [17]:
a.size # total number of elements

6

### many ways to create 1D arrays

In [18]:
# pass in a list to np.array()

a1 = np.array([1, 2, 3, 4, 5])

In [19]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
a1         ndarray    5: 5 elems, type `int32`, 20 bytes
a_list     list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [20]:
print( a1 )

[1 2 3 4 5]


In [21]:
# pass in a tuple

In [22]:
a2 = np.array((1, 2, 3, 4, 5))

In [23]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int32`, 24 bytes
a1         ndarray    5: 5 elems, type `int32`, 20 bytes
a2         ndarray    5: 5 elems, type `int32`, 20 bytes
a_list     list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [24]:
# if I want an array of only ZEROS

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
# if i want an array of only ONES

np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
0 * np.array([1, 2, 3, 4, 5])

array([0, 0, 0, 0, 0])

In [27]:
# np.arange() we can only specify a stepsize

np.arange(1, 12) # np.arange(start, end) -> [start, ..., end - 1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.arange(1, 12, 3) # np.arange(start, end, stepsize)

array([ 1,  4,  7, 10])

In [29]:
np.arange(1, 100, 20)

array([ 1, 21, 41, 61, 81])

In [30]:
np.linspace(0, 10, num=5) # np.linspace(start, end, num=<length of the array>)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.linspace(1, 15, num=21)

array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
        8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3, 15. ])

## MultiDimensional Array

### 2D array -- MATRIX

In [32]:
## a list of lists

[[0, 0, 0], 
 [1, 1, 1]]

[[0, 0, 0], [1, 1, 1]]

In [33]:
my_list_of_lists = [[0, 0, 0], [1, 1, 1]]

In [34]:
print( type(my_list_of_lists) )

<class 'list'>


In [35]:
# convert the list of lists into an ndarray
my_array = np.array(my_list_of_lists)

In [36]:
%whos

Variable           Type       Data/Info
---------------------------------------
a                  ndarray    6: 6 elems, type `int32`, 24 bytes
a1                 ndarray    5: 5 elems, type `int32`, 20 bytes
a2                 ndarray    5: 5 elems, type `int32`, 20 bytes
a_list             list       n=4
my_array           ndarray    2x3: 6 elems, type `int32`, 24 bytes
my_list_of_lists   list       n=2
np                 module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [37]:
print(my_array)

[[0 0 0]
 [1 1 1]]


In [38]:
print( my_list_of_lists )

[[0, 0, 0], [1, 1, 1]]


Attributes of my 2D array

In [39]:
print( my_array.ndim )

2


In [40]:
print( my_array.shape )

(2, 3)


In [41]:
print( my_array.size )

6


### slicing 2D arrays

Again slicing the 1D array looks like a list

In [42]:
a[ :3 ]

array([0, 1, 2])

In [43]:
a[ a >= 2 ]

array([2, 3, 4, 5])

In [44]:
a[ a%2 == 0 ] ## even 

array([0, 2, 4])

In [45]:
a[ a%2 != 0 ] ## odd

array([1, 3, 5])

For 2D arrays (or multidimensional arrays) we have to specify the dimension

In [46]:
my_array[0, 0]

0

In [47]:
my_array[0, 1]

0

In [48]:
my_array[1, 0]

1

In [49]:
my_array[0]

array([0, 0, 0])

In [50]:
my_array[1]

array([1, 1, 1])

In [51]:
my_array_1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])

In [52]:
print(my_array_1)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [53]:
my_array_1[2]

array([2, 2, 2])

In [54]:
my_array_1[2, :]

array([2, 2, 2])

In [55]:
my_array_1[0, :]

array([0, 0, 0])

In [56]:
### for all rows with a single COLUMN
my_array_1[:, 0]

array([0, 1, 2])

In [57]:
my_array_1[:, 1]

array([0, 1, 2])

In [58]:
### subset an array into another array
small_array = my_array_1[:, :2]

In [59]:
print( small_array )

[[0 0]
 [1 1]
 [2 2]]


In [60]:
print( my_array_1 )

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [61]:
small_array_b = my_array_1[:, :-1]

In [62]:
small_array_b

array([[0, 0],
       [1, 1],
       [2, 2]])

In [63]:
### arrays are mutable

small_array[0, 0] = 101
small_array[2, 1] = -101

In [64]:
print( small_array )

[[ 101    0]
 [   1    1]
 [   2 -101]]


In [65]:
print( my_array_1 )

[[ 101    0    0]
 [   1    1    1]
 [   2 -101    2]]


"VIEW" or a dynamic "window" to the larger object.

To make a "DEEP COPY" when subsetting we need to use the `.copy()`.

In [66]:
copy_array = my_array_1[:, :-1].copy()

In [67]:
print( copy_array )

[[ 101    0]
 [   1    1]
 [   2 -101]]


In [68]:
copy_array[0, 0] = -201
copy_array[-1, 1] = 501

In [69]:
print( copy_array )

[[-201    0]
 [   1    1]
 [   2  501]]


In [70]:
print( my_array_1 )

[[ 101    0    0]
 [   1    1    1]
 [   2 -101    2]]


### Concatenate arrays

In [71]:
my_1d_array = np.array([1, 2, 3])

my_1d_array_b = np.array([3, 2, 1])

In [72]:
np.concatenate([my_1d_array, my_1d_array_b])

array([1, 2, 3, 3, 2, 1])

In [73]:
### 2D arrays

b_2d_a = np.array([[0, 0, 0],
                 [1, 1, 1]])

b_2d_b = np.array([[2, 2, 2],
                 [3, 3, 3]])

In [74]:
print( b_2d_a )

print( b_2d_b )

[[0 0 0]
 [1 1 1]]
[[2 2 2]
 [3 3 3]]


In [75]:
print( b_2d_a )
print( '*--*--*')
print( b_2d_b )

[[0 0 0]
 [1 1 1]]
*--*--*
[[2 2 2]
 [3 3 3]]


In [76]:
### stack the two arrays together vertically

np.vstack((b_2d_a, b_2d_b) )

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [77]:
### "Bind" or stack horizontally

np.hstack((b_2d_a, b_2d_b) )

array([[0, 0, 0, 2, 2, 2],
       [1, 1, 1, 3, 3, 3]])

In [78]:
b_2d_a.shape

(2, 3)

In [79]:
b_2d_b.shape

(2, 3)

### reshaping

To convert an array of a particular dimensionality into another.

In [80]:
np.arange(1, 25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [81]:
np.arange(1, 25).reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [82]:
np.arange(1, 25).reshape(12, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [83]:
np.arange(1, 25).reshape(12, -1) # -1 is a shortcut which says whatever is needed

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [84]:
np.arange(1, 25).reshape(6, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [85]:
np.arange(1, 25).reshape(9, -1)

ValueError: cannot reshape array of size 24 into shape (9,newaxis)

## Array summary operations

In [86]:
X = np.arange(0, 24).reshape(6, -1)

In [87]:
X.shape

(6, 4)

In [88]:
print( X )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [89]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
### OVERALL MAX VALUE

X.max()

23

In [91]:
### OVERALL MIN

X.min()

0

In [92]:
### specify the AXIS to the summary methods
X.max(axis=0) # the PER COLUMN (down the rows)

array([20, 21, 22, 23])

In [93]:
### the min per column
X.min(axis=0)

array([0, 1, 2, 3])

In [94]:
### the max per ROW -- axis=1
X.max(axis=1)

array([ 3,  7, 11, 15, 19, 23])

In [95]:
X.min(axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [96]:
X.mean()

11.5

In [97]:
X.std()

6.922186552431729

### changing concanenating

In [98]:
my_combined_1d = np.concatenate([my_1d_array, my_1d_array_b])

In [99]:
my_combined_1d

array([1, 2, 3, 3, 2, 1])

In [100]:
my_combined_1d[0] = -100

In [101]:
my_combined_1d

array([-100,    2,    3,    3,    2,    1])

In [102]:
my_1d_array

array([1, 2, 3])

In [103]:
my_1d_array[2] = -500

In [104]:
my_1d_array

array([   1,    2, -500])

In [105]:
my_combined_1d

array([-100,    2,    3,    3,    2,    1])